### ISSUE TITLE
Implementation of Blog Page

### ISSUE THREAD

**Issue by bententhhousand** [Object-Obejct-mitr/B2RFrontend#19]
- [x] Wireframe Mockup of Blog Page on FIGMA (Run it by Matthew) Requirements: Screen to view most recent blog post + past blog posts, screen displaying tools to edit blog post
- [x] Basic integration of Quill (currently just to obtain the editor for layout implementation)
- [x] Layout implementation of screen to view most recent blog post + past blog posts
- [x] Dummy JSON Data to represent posts (Each post has a title, an Author, an HTML body, and an array of tags
- [x] Dynamic rendering of JSON Data onto page 
- [x] Layout implementation of screen to edit blog post, using editor from previously integrated Quill package
- [x] Further integration of Quill to combine with Firebase calls to save blog posts
- [x] Dynamic rendering of Firebase-fetched JSON Data

additional tasks:
- [x] implement some sort of virtual scroll when viewing recent blog posts
- [ ] some sort of pagination to handle lots of blog posts (maybe a stretch goal)

This (very long) youtube video has some great content to help get started here. It does a lot of things that we may not need to do, like authenticating and whatnot, just focus on integrating quill and connecting it to firebase.
https://www.youtube.com/watch?v=ISv22NNL-aE

**Comment by liuj-42** [comment]
Fix sorting by dates for the blog page
Make deleting a post make you go back to the main view
